package tlsprov

import (
	"context"
	"crypto/x509"
	"encoding/pem"
	"testing"
	"time"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func parseLeaf(t *testing.T, s *corev1.Secret) *x509.Certificate {
	t.Helper()
	block, _ := pem.Decode(secretBytes(s, KeyTLSCert))
	if block == nil {
		t.Fatal("no PEM block in tls.crt")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatalf("parsing leaf cert: %v", err)
	}
	return cert
}

func getSecret(t *testing.T, c client.Client, ns, name string) *corev1.Secret {
	t.Helper()
	var s corev1.Secret
	if err := c.Get(context.Background(), types.NamespacedName{Namespace: ns, Name: name}, &s); err != nil {
		t.Fatalf("getting %s/%s: %v", ns, name, err)
	}
	return &s
}

func TestEnsure_FirstRunGeneratesACAAndAValidLeaf(t *testing.T) {
	ctx := context.Background()
	c := fake.NewClientBuilder().Build()

	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "booth.home.arpa"); err != nil {
		t.Fatal(err)
	}

	leaf := getSecret(t, c, "booth-system", "booth-core-tls")
	if leaf.Type != corev1.SecretTypeTLS {
		t.Errorf("leaf secret type = %v, want kubernetes.io/tls", leaf.Type)
	}
	cert := parseLeaf(t, leaf)
	if len(cert.DNSNames) != 1 || cert.DNSNames[0] != "booth.home.arpa" {
		t.Errorf("leaf SAN = %v, want [booth.home.arpa]", cert.DNSNames)
	}
	if time.Until(cert.NotAfter) > leafValidity || time.Until(cert.NotAfter) < leafValidity-time.Hour*2 {
		t.Errorf("leaf NotAfter = %v, want ~%v from now", cert.NotAfter, leafValidity)
	}

	ca := getSecret(t, c, "booth-system", "booth-core-tls-ca")
	if time.Until(parseLeaf(t, ca).NotAfter) < leafValidity {
		t.Error("CA should be long-lived, well beyond the leaf's own validity")
	}

	// The CA's exported public cert actually verifies the leaf -- not just present, usable.
	pool := x509.NewCertPool()
	pool.AddCert(parseLeaf(t, ca))
	if _, err := cert.Verify(x509.VerifyOptions{DNSName: "booth.home.arpa", Roots: pool}); err != nil {
		t.Errorf("leaf does not verify against the exported CA: %v", err)
	}
	if string(secretBytes(leaf, KeyCACert)) == "" {
		t.Error("leaf secret should also carry the CA's public cert (ca.crt) for an operator to retrieve")
	}
}

func TestEnsure_SecondRunLeavesAFreshLeafAlone(t *testing.T) {
	ctx := context.Background()
	c := fake.NewClientBuilder().Build()

	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "booth.home.arpa"); err != nil {
		t.Fatal(err)
	}
	first := getSecret(t, c, "booth-system", "booth-core-tls")

	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "booth.home.arpa"); err != nil {
		t.Fatal(err)
	}
	second := getSecret(t, c, "booth-system", "booth-core-tls")

	if string(secretBytes(first, KeyTLSCert)) != string(secretBytes(second, KeyTLSCert)) {
		t.Error("a fresh, matching-host leaf should not be re-issued")
	}
}

func TestEnsure_ReissuesWithin30DaysOfExpiry(t *testing.T) {
	ctx := context.Background()
	c := fake.NewClientBuilder().Build()

	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "booth.home.arpa"); err != nil {
		t.Fatal(err)
	}
	ca := getSecret(t, c, "booth-system", "booth-core-tls-ca")

	// Simulate a leaf that's 10 days from expiry, signed by the real CA (so it would otherwise
	// verify fine) -- the only thing wrong with it is its age.
	caPair, ok := parseCA(ca)
	if !ok {
		t.Fatal("couldn't parse the CA this test just created")
	}
	oldCertPEM, oldKeyPEM, err := issueLeaf(caPair, "booth.home.arpa", 10*24*time.Hour)
	if err != nil {
		t.Fatal(err)
	}
	leaf := getSecret(t, c, "booth-system", "booth-core-tls")
	leaf.Data = map[string][]byte{KeyTLSCert: oldCertPEM, KeyTLSKey: oldKeyPEM, KeyCACert: secretBytes(ca, KeyTLSCert)}
	if err := c.Update(ctx, leaf); err != nil {
		t.Fatal(err)
	}

	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "booth.home.arpa"); err != nil {
		t.Fatal(err)
	}
	renewed := getSecret(t, c, "booth-system", "booth-core-tls")
	renewedCert := parseLeaf(t, renewed)
	if time.Until(renewedCert.NotAfter) < 300*24*time.Hour {
		t.Errorf("leaf should have been re-issued fresh (~1 year out); NotAfter = %v", renewedCert.NotAfter)
	}

	// Re-issued under the SAME CA -- a CA an operator already imported keeps working.
	caSecondRead := getSecret(t, c, "booth-system", "booth-core-tls-ca")
	if string(secretBytes(ca, KeyTLSCert)) != string(secretBytes(caSecondRead, KeyTLSCert)) {
		t.Error("the CA itself should never be regenerated by a leaf renewal")
	}
}

func TestEnsure_ReissuesWhenHostChanges(t *testing.T) {
	ctx := context.Background()
	c := fake.NewClientBuilder().Build()

	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "old.example"); err != nil {
		t.Fatal(err)
	}
	if err := Ensure(ctx, c, "booth-system", "booth-core-tls", "new.example"); err != nil {
		t.Fatal(err)
	}

	leaf := getSecret(t, c, "booth-system", "booth-core-tls")
	cert := parseLeaf(t, leaf)
	if len(cert.DNSNames) != 1 || cert.DNSNames[0] != "new.example" {
		t.Errorf("leaf SAN = %v, want [new.example] after ingress.host changed", cert.DNSNames)
	}
}
