package natsauth

import (
	"fmt"
	"strings"
	"time"

	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"
)

// Seeds are the private keys behind the event bus's trust chain. They're generated once,
// stored in a Kubernetes Secret (see LoadOrCreate), and never leave core's namespace.
type Seeds struct {
	Operator string // signs the account JWT; needed only to change the account itself
	Account  string // the BOOTH account's identity key
	Signing  string // the account signing key core uses to mint user credentials
	System   string // the system account's identity key (JetStream requires one)
}

// GenerateSeeds creates a fresh operator, account, account-signing, and system key.
func GenerateSeeds() (Seeds, error) {
	var s Seeds
	for _, spec := range []struct {
		dst *string
		mk  func() (nkeys.KeyPair, error)
	}{
		{&s.Operator, nkeys.CreateOperator},
		{&s.Account, nkeys.CreateAccount},
		{&s.Signing, nkeys.CreateAccount},
		{&s.System, nkeys.CreateAccount},
	} {
		kp, err := spec.mk()
		if err != nil {
			return Seeds{}, fmt.Errorf("generating nkey: %w", err)
		}
		seed, err := kp.Seed()
		if err != nil {
			return Seeds{}, fmt.Errorf("encoding nkey seed: %w", err)
		}
		*spec.dst = string(seed)
	}
	return s, nil
}

// Authority mints user credentials for the event bus and renders the server-side trust
// configuration that makes the NATS server accept them.
type Authority struct {
	operatorKP nkeys.KeyPair
	accountKP  nkeys.KeyPair
	signingKP  nkeys.KeyPair
	systemKP   nkeys.KeyPair
	accountPub string
	signingPub string
	now        func() time.Time
}

// NewAuthority builds an Authority from previously generated seeds.
func NewAuthority(s Seeds) (*Authority, error) {
	a := &Authority{now: time.Now}
	var err error
	if a.operatorKP, err = nkeys.FromSeed([]byte(s.Operator)); err != nil {
		return nil, fmt.Errorf("operator seed: %w", err)
	}
	if a.accountKP, err = nkeys.FromSeed([]byte(s.Account)); err != nil {
		return nil, fmt.Errorf("account seed: %w", err)
	}
	if a.signingKP, err = nkeys.FromSeed([]byte(s.Signing)); err != nil {
		return nil, fmt.Errorf("signing seed: %w", err)
	}
	if a.systemKP, err = nkeys.FromSeed([]byte(s.System)); err != nil {
		return nil, fmt.Errorf("system account seed: %w", err)
	}
	if a.accountPub, err = a.accountKP.PublicKey(); err != nil {
		return nil, err
	}
	if a.signingPub, err = a.signingKP.PublicKey(); err != nil {
		return nil, err
	}
	return a, nil
}

// AccountPublicKey identifies the account; it changes only if the seeds are regenerated.
func (a *Authority) AccountPublicKey() string { return a.accountPub }

// ServerConfig renders the NATS server configuration fragment (included from the main
// nats.conf by the Helm chart) establishing this Authority as the sole trust root:
// the operator JWT, the BOOTH account (JetStream enabled) every participant lives in, and
// the system account JetStream requires, preloaded into an in-memory resolver. Adding
// modules never changes this file.
func (a *Authority) ServerConfig() (string, error) {
	opPub, err := a.operatorKP.PublicKey()
	if err != nil {
		return "", err
	}
	sysPub, err := a.systemKP.PublicKey()
	if err != nil {
		return "", err
	}

	oc := jwt.NewOperatorClaims(opPub)
	oc.Name = "booth"
	oc.SystemAccount = sysPub
	opJWT, err := oc.Encode(a.operatorKP)
	if err != nil {
		return "", fmt.Errorf("encoding operator JWT: %w", err)
	}

	ac := jwt.NewAccountClaims(a.accountPub)
	ac.Name = "BOOTH"
	ac.SigningKeys.Add(a.signingPub)
	// -1 is "unlimited" for JetStream limits. Actual capacity is bounded by the PVC the
	// Helm chart provisions for the JetStream file store, not by an arbitrary quota here.
	ac.Limits.JetStreamLimits = jwt.JetStreamLimits{
		MemoryStorage: -1, DiskStorage: -1, Streams: -1, Consumer: -1,
	}
	acJWT, err := ac.Encode(a.operatorKP)
	if err != nil {
		return "", fmt.Errorf("encoding account JWT: %w", err)
	}

	sysClaims := jwt.NewAccountClaims(sysPub)
	sysClaims.Name = "SYS"
	sysJWT, err := sysClaims.Encode(a.operatorKP)
	if err != nil {
		return "", fmt.Errorf("encoding system account JWT: %w", err)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by booth-core (ADR 0049). Do not edit by hand.\n")
	fmt.Fprintf(&b, "operator: %q\n", opJWT)
	fmt.Fprintf(&b, "system_account: %s\n", sysPub)
	fmt.Fprintf(&b, "resolver: MEMORY\n")
	fmt.Fprintf(&b, "resolver_preload: {\n  %s: %q\n  %s: %q\n}\n", a.accountPub, acJWT, sysPub, sysJWT)
	return b.String(), nil
}

// Credential is a minted user identity for the event bus.
type Credential struct {
	JWT       string
	Seed      string
	Creds     []byte // the standard NATS ".creds" file content (JWT + seed)
	ExpiresAt time.Time
}

// MintUser creates a user credential named name, valid for ttl, allowed to publish and
// subscribe only to the given grants. Anything not granted is denied by the server.
func (a *Authority) MintUser(name string, g Grants, ttl time.Duration) (*Credential, error) {
	ukp, err := nkeys.CreateUser()
	if err != nil {
		return nil, fmt.Errorf("generating user key: %w", err)
	}
	upub, err := ukp.PublicKey()
	if err != nil {
		return nil, err
	}
	seed, err := ukp.Seed()
	if err != nil {
		return nil, err
	}

	expires := a.now().Add(ttl)
	uc := jwt.NewUserClaims(upub)
	uc.Name = name
	uc.IssuerAccount = a.accountPub // marks the signer as one of the account's signing keys
	uc.Expires = expires.Unix()
	uc.Pub.Allow.Add(g.PublishAllow...)
	uc.Sub.Allow.Add(g.SubscribeAllow...)

	token, err := uc.Encode(a.signingKP)
	if err != nil {
		return nil, fmt.Errorf("encoding user JWT: %w", err)
	}
	creds, err := jwt.FormatUserConfig(token, seed)
	if err != nil {
		return nil, fmt.Errorf("formatting creds: %w", err)
	}
	return &Credential{JWT: token, Seed: string(seed), Creds: creds, ExpiresAt: expires}, nil
}
