{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "booth-core.fullname" . }}
  labels:
    {{- include "booth-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOOTH_IFRAME_SIGNING_KEY: {{ .Values.iframeSigningKey | quote }}
  {{- if .Values.postgres.dsn }}
  BOOTH_POSTGRES_DSN: {{ .Values.postgres.dsn | quote }}
  {{- end }}
{{- end }}
