package integration

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/nats-io/jwt/v2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"

	boothv1alpha1 "github.com/projectbooth/booth-core/api/v1alpha1"
	"github.com/projectbooth/booth-core/internal/natsauth"
)

// TestEventBusAuth_AgainstRealAPIServer runs the ADR 0049 bootstrap and per-module
// provisioning against a real kube-apiserver. The fake client used elsewhere can't catch
// what only a real API server enforces: that the BoothModule schema admits the new
// `events` field (and rejects a widening pattern), that a Secret's StringData becomes
// readable Data, and that the ownerReference we set is one Kubernetes accepts.
func TestEventBusAuth_AgainstRealAPIServer(t *testing.T) {
	testEnv := &envtest.Environment{
		CRDDirectoryPaths:     []string{filepath.Join("..", "..", "config", "crd", "bases")},
		ErrorIfCRDPathMissing: true,
	}
	cfg, err := testEnv.Start()
	if err != nil {
		t.Fatalf("starting envtest: %v", err)
	}
	t.Cleanup(func() { _ = testEnv.Stop() })

	sch := runtime.NewScheme()
	if err := scheme.AddToScheme(sch); err != nil {
		t.Fatal(err)
	}
	if err := boothv1alpha1.AddToScheme(sch); err != nil {
		t.Fatal(err)
	}
	c, err := client.New(cfg, client.Options{Scheme: sch})
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	for _, name := range []string{"booth-system", "booth-superset"} {
		if err := c.Create(ctx, &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: name}}); err != nil {
			t.Fatal(err)
		}
	}

	// Bootstrap: keys Secret + server-config ConfigMap, idempotent on a second run.
	a1, err := natsauth.LoadOrCreate(ctx, c, "booth-system")
	if err != nil {
		t.Fatalf("LoadOrCreate: %v", err)
	}
	a2, err := natsauth.LoadOrCreate(ctx, c, "booth-system")
	if err != nil {
		t.Fatal(err)
	}
	if a1.AccountPublicKey() != a2.AccountPublicKey() {
		t.Fatal("bootstrap is not idempotent against a real API server")
	}
	var cm corev1.ConfigMap
	if err := c.Get(ctx, types.NamespacedName{Namespace: "booth-system", Name: natsauth.AuthConfigMapName}, &cm); err != nil {
		t.Fatalf("server-config ConfigMap: %v", err)
	}
	if !strings.HasPrefix(cm.Data[natsauth.AuthConfigKey], "# Generated by booth-core") {
		t.Errorf("unexpected server config: %.80q", cm.Data[natsauth.AuthConfigKey])
	}

	// The CRD schema must reject a pattern that would widen access, before core ever sees it.
	bad := &boothv1alpha1.BoothModule{
		ObjectMeta: metav1.ObjectMeta{Name: "evil", Namespace: "booth-superset"},
		Spec: boothv1alpha1.BoothModuleSpec{
			ID: "evil", DisplayName: "Evil", Version: "0", ContractVersion: "0", HealthCheckPath: "/h",
			ServiceRef: boothv1alpha1.ServiceReference{Name: "s", Port: 80},
			Events:     &boothv1alpha1.EventBusAccess{Publish: []string{">"}},
		},
	}
	if err := c.Create(ctx, bad); err == nil {
		t.Error("the API server accepted a BoothModule declaring publish access to \">\"")
	}

	// A legitimate module.
	mod := &boothv1alpha1.BoothModule{
		ObjectMeta: metav1.ObjectMeta{Name: "superset", Namespace: "booth-superset"},
		Spec: boothv1alpha1.BoothModuleSpec{
			ID: "superset", DisplayName: "Superset", Version: "0.1.0", ContractVersion: "0.1.0",
			HealthCheckPath: "/health",
			ServiceRef:      boothv1alpha1.ServiceReference{Name: "superset", Namespace: "booth-superset", Port: 8088},
			Events:          &boothv1alpha1.EventBusAccess{Publish: []string{"dashboard.*"}},
		},
	}
	if err := c.Create(ctx, mod); err != nil {
		t.Fatalf("creating BoothModule with events: %v", err)
	}

	p := natsauth.NewModuleProvisioner(c, a1, "nats://booth-core-nats.booth-system.svc.cluster.local:4222")
	if err := p.Ensure(ctx, mod); err != nil {
		t.Fatalf("Ensure: %v", err)
	}

	var sec corev1.Secret
	if err := c.Get(ctx, types.NamespacedName{Namespace: "booth-superset", Name: natsauth.CredentialsSecretName}, &sec); err != nil {
		t.Fatalf("credential Secret: %v", err)
	}
	// Real API servers convert StringData to Data.
	token, err := jwt.ParseDecoratedJWT(sec.Data[natsauth.CredsKey])
	if err != nil {
		t.Fatalf("stored credential isn't a valid .creds file: %v", err)
	}
	uc, err := jwt.DecodeUserClaims(token)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(strings.Join(uc.Pub.Allow, ","), "booth.*.dashboard.*") {
		t.Errorf("publish allow-list = %v", uc.Pub.Allow)
	}
	if string(sec.Data[natsauth.URLKey]) != p.URL {
		t.Errorf("url = %q", sec.Data[natsauth.URLKey])
	}
	if len(sec.OwnerReferences) != 1 || sec.OwnerReferences[0].UID != mod.UID {
		t.Errorf("ownerReferences = %v, want the BoothModule (uid %s)", sec.OwnerReferences, mod.UID)
	}

	var n corev1.Namespace
	if err := c.Get(ctx, types.NamespacedName{Name: "booth-superset"}, &n); err != nil {
		t.Fatal(err)
	}
	if n.Labels[natsauth.ClientNamespaceLabel] != "true" {
		t.Error("module namespace not labelled for the NATS NetworkPolicy")
	}

	// A second reconcile must not churn the credential.
	before := string(sec.Data[natsauth.CredsKey])
	if err := p.Ensure(ctx, mod); err != nil {
		t.Fatal(err)
	}
	if err := c.Get(ctx, types.NamespacedName{Namespace: "booth-superset", Name: natsauth.CredentialsSecretName}, &sec); err != nil {
		t.Fatal(err)
	}
	if string(sec.Data[natsauth.CredsKey]) != before {
		t.Error("credential was re-minted on a no-op reconcile against a real API server")
	}
}
